// <auto-generated />
namespace TabMenu2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class p1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(p1));
        
        string IMigrationMetadata.Id
        {
            get { return "202004061931555_p1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
